/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeLib */

#ifndef _Included_NativeLib
#define _Included_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeLib
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeLib_print
  (JNIEnv *, jobject);

/*
 * Class:     NativeLib
 * Method:    print2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeLib_print2
  (JNIEnv *, jobject);

/*
 * Class:     NativeLib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeLib_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeLib
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeLib_sub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
